#!/usr/bin/env zsh
# vim: syn=zsh

export GOPATH="$HOME/.local/go"
export GO_BIN="$HOME/.local/bin.go"
export NPM_BIN="$HOME/.npm-global/bin"


path=(
    $GO_BIN
    $NPM_BIN
    $path)
# vim: syn=zsh
