#!/usr/bin/env zsh
# vim: syn=zsh

# Executes commands at login post-zshrc.
#
# Execute code that does not affect the current session in the background.

( autoload -Uz colors && colors ) &!
{
  # Compile the completion dump to increase startup speed.
  #
  zcompdump="${ZSH_CACHE}/zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!
env_loader zlogin
